// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8B80QNdSfCeEJPwoSrOHZLECYCNmvZIk',
    appId: '1:311302968084:web:78057ed1c051ec02cc2801',
    messagingSenderId: '311302968084',
    projectId: 'flutterfullstack-9448e',
    authDomain: 'flutterfullstack-9448e.firebaseapp.com',
    storageBucket: 'flutterfullstack-9448e.appspot.com',
    measurementId: 'G-BK2NNYT2MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYVWVzmNuZ9ZHuhtg2wJJBwPcmlzoIOSA',
    appId: '1:311302968084:android:668f2d5f002acab8cc2801',
    messagingSenderId: '311302968084',
    projectId: 'flutterfullstack-9448e',
    storageBucket: 'flutterfullstack-9448e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbMpN022Fue1y9Hg_yEoZSB2ixxtJ3WEM',
    appId: '1:311302968084:ios:dfca51f67f513f91cc2801',
    messagingSenderId: '311302968084',
    projectId: 'flutterfullstack-9448e',
    storageBucket: 'flutterfullstack-9448e.appspot.com',
    iosBundleId: 'com.example.flutterFullStack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbMpN022Fue1y9Hg_yEoZSB2ixxtJ3WEM',
    appId: '1:311302968084:ios:dfca51f67f513f91cc2801',
    messagingSenderId: '311302968084',
    projectId: 'flutterfullstack-9448e',
    storageBucket: 'flutterfullstack-9448e.appspot.com',
    iosBundleId: 'com.example.flutterFullStack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8B80QNdSfCeEJPwoSrOHZLECYCNmvZIk',
    appId: '1:311302968084:web:e0f1a42786fccb2ccc2801',
    messagingSenderId: '311302968084',
    projectId: 'flutterfullstack-9448e',
    authDomain: 'flutterfullstack-9448e.firebaseapp.com',
    storageBucket: 'flutterfullstack-9448e.appspot.com',
    measurementId: 'G-3JRESB50ZE',
  );

}